# Start with a base image containing Java runtime
FROM openjdk:8-jdk-alpine

# Add Maintainer Info
LABEL maintainer="sergey.v.karpushin@gmail.com"

# Add a volume pointing to /tmp
VOLUME /tmp

# Make port 8080 available to the world outside this container
EXPOSE 8080
EXPOSE 47500-47505
EXPOSE 47100-47105

# The application's jar file
ARG JAR_FILE=issue20181122-0.0.1-SNAPSHOT.jar

# Add the application's jar to the container
COPY ${JAR_FILE} webapp.jar
COPY keystore.jks keystore.jks

# Run the jar file 
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/webapp.jar"]
